import { launchBrowser } from "@/lib/browser";
import { NextResponse } from "next/server";

export const runtime = "nodejs";
export const maxDuration = 60;

type ReportStep = {
  name: string;
  url: string;
  status: string;
  speedLight: string;
  journeyLight: string;
  trafficLight: string;
  durationMs: number;
  likelyCause: string;
  issues: string[];
  inefficiencies: string[];
};

type ReportInput = {
  title?: string;
  overview?: string;
  speedSummary?: string;
  recommendations?: { title: string; action: string; reason: string }[];
  steps?: ReportStep[];
};

function escapeHtml(value: unknown) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function lightClass(value: string) {
  return value === "green" ? "green" : value === "orange" ? "orange" : "red";
}

export async function POST(request: Request) {
  let input: ReportInput;
  try {
    input = await request.json();
  } catch {
    return NextResponse.json({ error: "Report data must be valid JSON." }, { status: 400 });
  }

  let browser;
  try {
    browser = await launchBrowser();
    const page = await browser.newPage();
    const steps = input.steps || [];
    const recommendations = input.recommendations || [];
    const html = `<!doctype html><html><head><meta charset="utf-8"><style>
      @page { size: A4; margin: 18mm; }
      * { box-sizing: border-box; }
      body { color: #172033; font-family: Arial, sans-serif; font-size: 10pt; line-height: 1.45; }
      h1 { color: #0f172a; font-size: 24pt; margin: 0 0 6px; }
      h2 { border-bottom: 1px solid #cbd5e1; color: #0f172a; font-size: 15pt; margin: 22px 0 10px; padding-bottom: 5px; }
      h3 { color: #0f172a; font-size: 11pt; margin: 0 0 5px; }
      p { margin: 5px 0; }
      .muted { color: #64748b; }
      .summary { background: #f1f5f9; border-left: 4px solid #38bdf8; margin: 14px 0; padding: 10px 12px; }
      .recommendation, .step { border: 1px solid #cbd5e1; margin: 8px 0; padding: 10px 12px; page-break-inside: avoid; }
      .number { color: #0284c7; font-weight: bold; margin-right: 7px; }
      .badges { margin: 5px 0; }
      .badge { border-radius: 3px; display: inline-block; font-size: 8pt; font-weight: bold; margin-right: 6px; padding: 2px 6px; text-transform: uppercase; }
      .green { background: #dcfce7; color: #166534; }
      .orange { background: #fef3c7; color: #92400e; }
      .red { background: #fee2e2; color: #991b1b; }
      .url { color: #475569; font-size: 8pt; overflow-wrap: anywhere; }
      ul { margin: 5px 0 0 18px; padding: 0; }
      footer { color: #64748b; font-size: 8pt; margin-top: 24px; }
    </style></head><body>
      <h1>${escapeHtml(input.title || "Journey quality report")}</h1>
      <p class="muted">Generated by Web Quality Agent</p>
      <div class="summary"><strong>Journey overview</strong><p>${escapeHtml(input.overview)}</p><p>${escapeHtml(input.speedSummary)}</p></div>
      <h2>Top recommended improvements</h2>
      ${recommendations.length ? recommendations.map((item, index) => `<div class="recommendation"><h3><span class="number">${String(index + 1).padStart(2, "0")}</span>${escapeHtml(item.title)}</h3><p><strong>Do:</strong> ${escapeHtml(item.action)}</p><p class="muted"><strong>Why it matters:</strong> ${escapeHtml(item.reason)}</p></div>`).join("") : "<p>No recommendations were generated.</p>"}
      <h2>Journey steps</h2>
      ${steps.map((step, index) => `<div class="step"><h3><span class="number">${String(index + 1).padStart(2, "0")}</span>${escapeHtml(step.name)}</h3><div class="badges"><span class="badge ${lightClass(step.trafficLight)}">Overall ${escapeHtml(step.trafficLight)}</span><span class="badge ${lightClass(step.speedLight)}">Speed ${escapeHtml(step.speedLight)}</span><span class="badge ${lightClass(step.journeyLight)}">Journey ${escapeHtml(step.journeyLight)}</span><span class="badge ${step.status === "complete" ? "green" : "red"}">${escapeHtml(step.status)}</span></div><p class="url">${escapeHtml(step.url)}</p><p><strong>Load time:</strong> ${(step.durationMs / 1000).toFixed(2)} seconds</p><p>${escapeHtml(step.likelyCause)}</p>${step.issues?.length ? `<p><strong>Issues to fix:</strong></p><ul>${step.issues.map((issue) => `<li>${escapeHtml(issue)}</li>`).join("")}</ul>` : ""}${step.inefficiencies?.length ? `<p><strong>Repeatable checks:</strong></p><ul>${step.inefficiencies.map((issue) => `<li>${escapeHtml(issue)}</li>`).join("")}</ul>` : ""}</div>`).join("")}
      <footer>This report is a point-in-time browser measurement. Re-run it for each key country, device, and release.</footer>
    </body></html>`;
    await page.setContent(html, { waitUntil: "load" });
    const pdf = await page.pdf({ format: "A4", printBackground: true });
    return new NextResponse(new Uint8Array(pdf), { status: 200, headers: { "Content-Type": "application/pdf", "Content-Disposition": "attachment; filename=journey-quality-report.pdf", "Content-Length": String(pdf.length) } });
  } catch (error) {
    console.error("Could not create journey report.", error);
    return NextResponse.json({ error: "The PDF report could not be created." }, { status: 500 });
  } finally {
    await browser?.close();
  }
}
